'use strict';
var ball = {
  color: {
    red: '#f00',
    green: '#0f0',
    blue: '#00f'
  },
  answers: {
    html: [
      'Did you close your tags',
      'Is your computer on',
      'HTML defines content of web pages',
      'HTML documents start with: <!DOCTYPE html>',
      'HTML document begins with <html> ends with </html>',
      'The visible part of the HTML document: <body> and </body>',
      'HTML paragraphs use <p> tag',
      'HTML link: <a> tag, the link\'s destination href attribute. ',
      'HTML images use the <img> tag',
      '.class is for elements with a \'class\'',
      '#id is for elements with an \'id\'',
      'HTML stands for Hyper Text Markup Language',
      'HTML elements are represented by tags',
      'First tag: start tag, second tag: end tag',
      'fonts.google.com',
      'Line break <br/>',
      '<center>Centering</center>',
      '<ol><li>Ordered List</li></ol>',
      '<ul><li>Unordered List</li></ol>',
      'HTML headings: <h1> to <h6> tags'
    ],
    css: [
      'Are you closing your elements',
      'Did you forget the semicolon',
      'CSS specifies web page layout',
      'CSS stands for Cascading Style Sheets',
      'CSS describes how HTML elements are to be displayed',
      'Yes! CSS can control the layout of multiple web pages',
      'CSS in HTML elements: Inline, Internal and External',
      'Inline: using the style attribute in HTML elements',
      'Internal: using a <style> element in the <head> section',
      'External: using an external CSS file',
      'External style sheet: link goes in the <head>',
      'CSS color property:  the text color to be used',
      'CSS font-family: the font to be used',
      'Margin, border, padding, content',
      'Selectors indicate which element the rule applies to',
      'Properties indicate aspects of the element you want to change',
      'Values specify settings you want to use for the chosen properties',
      'Declarations indicate how elements are referred to in selector should be styled',
      'Fixed positioning stays in place when page is scrolled',
      'CSS font-size: the text size to be used'
    ],
    js: [
      'Are you calling your variables',
      'Check your spelling',
      'JavaScript programs the behavior of web pages',
      'Variables are containers that you can store values in',
      'Declare a variable with the keyword var',
      'An operator produces a result of two values (or variables)',
      'JavaScript is a case-sensitive.',
      'Global variables are defined outside a function',
      'Local variables are defined within a function',
      'Function parameters are always local to that function',
      'Don\'t forget your semicolon',
      'All JavaScript values, except primitives, are objects',
      'JavaScript methods are actions that can be performed on objects',
      'A JavaScript method is a property containing a function definition',
      'Methods are actions that can be perfomed on objects',
      'Methods are stored in properties as function definitions',
      'You define (and create) JavaScript objects with an object literal',
      'Math.round(x) returns the value of x rounded to its nearest integer',
      'A method is a function definition stored as a property value',
      '4 + 5: The ‘+’ is called the operator'
    ],
    motivation: [
      'The secret of getting ahead is getting started.',
      'It\'s gonna be ok',
      'Either you run the day or the day runs you.',
      'Step by step and the thing is done.',
      'Learning is about leaving your comfort zone.',
      'Well done is better than well said.',
      'If you’re going through hell, keep going.',
      'There is no such thing as failure. There are only results.',
      'Yes, the pace is fast for everybody',
      'Trust the process',
      'It usually clicks for most in 301',
      'It will all make sense later',
      'Stacked learning. Stacked learning. Stacked learning',
      'Mental attitude is more important than mental capacity.',
      'Expect problems and eat them for breakfast.',
      'Programming is the art of adding bugs to an empty text file.',
      'It does not matter how slowly you go as long as you do not stop.',
      'Success is the sum of small efforts, repeated day in and day out.',
      'Programming is 10% writing code, 90% fixing your bugs',
      'A stacked learning style is meant to be challenging'
    ],
    traditional: [
      'It is certain',
      'It is decidedly so',
      'Without a doubt',
      'Yes definitely',
      'You may rely on it',
      'As I see it, yes',
      'Most likely',
      'Outlook good',
      'Yes',
      'Signs point to yes',
      'Reply hazy try again',
      'Ask again later',
      'Better not tell you now',
      'Cannot predict now',
      'Concentrate and ask again',
      'Don\'t count on it',
      'My reply is no',
      'My sources say no',
      'Outlook not so good',
      'Very doubtful'
    ],
    recommendations: [
      'Take a break',
      'Struggling? Take a break',
      'Reread the material',
      'Go to YouTube channel, watch the video',
      'Rubber ducky',
      'Walk around the block',
      'ACP',
      'Check your spelling',
      'Check the googles',
      'Read the docs',
      'Slow down, take smaller steps',
      'Plan it out',
      'Make a to do list',
      'First, solve the problem. Then, write the code',
      'Check Stack Overflow',
      'Look at cat pictures',
      'Get up and stretch',
      'Go play ping pong',
      'Ask for help',
      'Peer program',
      'Use online resources',
      'Reduce complexity to simplicity',
      'Remove any code that isn\'t being used',
      'Don\'t repeat yourself'
    ]

  }
};
